[project]
name = "course-agents"
version = "0.1.0"
description = "Agents course"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["smolagents[litellm]>=1.14.0"]

[dependency-groups]
dev = ["ipykernel>=6.29.5"]
